# Generated by Django 3.1.5 on 2023-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
